### ISSUE TITLE
ImportError: cannot import name 'config' from 'settings'

### ISSUE THREAD

**Issue by huseyincenik** [MisterClean/ChicagoYIMBYblueskybot#2]
Hello, I encountered the following error while trying to run the project:

Traceback (most recent call last):
  File "C:\Users\***ChicagoYIMBYblueskybot\src\main.py", line 3, in <module>
    from bot.bot_logic import BotLogic
  File "C:\Users\***ChicagoYIMBYblueskybot\src\bot\bot_logic.py", line 6, in <module>
    from bot.post_handler import PostHandler
  File "C:\Users\***ChicagoYIMBYblueskybot\src\bot\post_handler.py", line 3, in <module>
    from utils.rss_parser import fetch_image_url
  File "C:\Users\***ChicagoYIMBYblueskybot\src\utils\rss_parser.py", line 10, in <module>
    from settings import config
ImportError: cannot import name 'config' from 'settings' (C:\Users\***ChicagoYIMBYblueskybot\src\settings.py)

**Comment by PileOfGarbage** [comment]
I resolved this issue by modifying `settings.py` as below (Quick-and-dirty fix, not optimal):

```python
import os
import logging
import yaml
from dotenv import load_dotenv
from datetime import datetime

logger = logging.getLogger(__name__)

load_dotenv()

BLUESKY_USERNAME = os.getenv("BLUESKY_USERNAME")
BLUESKY_PASSWORD = os.getenv("BLUESKY_PASSWORD")
RSS_FEED_URL = os.getenv("RSS_FEED_URL")

# Minimum date for RSS entries to be posted (default to November 13, 2024)
MIN_POST_DATE = os.getenv("MIN_POST_DATE", "2024-11-13")
MIN_POST_DATE = datetime.strptime(MIN_POST_DATE, "%Y-%m-%d")

def load_config():
    """Load configuration from YAML file."""
    try:
        config_path = os.path.join(os.path.dirname(__file__), '../config.yaml')
        with open(config_path, 'r') as f:
            return yaml.safe_load(f)
    except Exception as e:
        logger.critical(f"Failed to load config file: {e}")
        raise

config = load_config()
```

**Comment by huseyincenik** [comment]
Thanks for this. It says that ffeed cannot parse the file. Can you explain what kind of feed link should I send?
![image](https://github.com/user-attachments/assets/847119ee-69b2-4a3b-9feb-1afa806f7103)

**Comment by PileOfGarbage** [comment]
The `RSS_FEED_URL` setting in your [`.env`](https://github.com/MisterClean/ChicagoYIMBYblueskybot?tab=readme-ov-file#3-set-up-environment-variables) must be set to a well-formed URI pointing to a valid RSS feed file. This file should be in XML and conform to a spec supported by [feedparser](https://feedparser.readthedocs.io/en/latest/introduction.html#introduction) (Ideally [RSS 2.0](https://www.rssboard.org/rss-specification)).

For example, here is the URI for the [Slashdot](https://slashdot.org/) front-page RSS feed: <https://rss.slashdot.org/Slashdot/slashdotMain>.

**Comment by huseyincenik** [comment]
I am doing what you said, I am selecting the site you sent as feed, but it
still gives an error
